cache:
  mount:
    - /drone/src
    - /drone/pkg

clone:
  depth: 50
  path: portal-server

build:
  api:
    image: golang:1.5
    commands:
      - go get -u github.com/asaskevich/govalidator
      - go get -u github.com/gin-gonic/gin
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/jinzhu/gorm
      - go get -u github.com/mattn/go-sqlite3
      - go get -u github.com/satori/go.uuid
      - go get -u github.com/stretchr/testify/assert
      - go get -u golang.org/x/crypto/pbkdf2
      - golint ./api/...
      - go test -cover ./api/...
  gcm:
    image: golang:1.5
    commands:
      - go get -u github.com/asaskevich/govalidator
      - go get -u github.com/google/go-gcm
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/jinzhu/gorm
      - go get -u github.com/mattn/go-sqlite3
      - go get -u github.com/satori/go.uuid
      - go get -u github.com/stretchr/testify/assert
      - golint ./gcm/...
      - go test -cover ./gcm/...

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone

publish:
  gcr:
    when:
      branch: master
    repo: gcr.io/messaging-1174/portal/api
    file: Dockerfile.api
    token: >
      $$GCR_KEY
  gcr:
    when:
      branch: master
    repo: gcr.io/messaging-1174/portal/gcm
    file: Dockerfile.gcm
    token: >
      $$GCR_KEY
