cache:
  mount:
    - vendor/

clone:
  path: portal-server

build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - go test -cover ./api/... ./gcm/... ./store/...

compose:
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone

publish:
  gcr:
    when:
      event: tag
    repo: gcr.io/messaging-1174/portal-server
    token: >
      $$GCR_KEY
