cache:
  mount:
    - /drone/src
    - /drone/pkg

clone:
  depth: 50
  path: portal-server

build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - go get github.com/tools/godep
    - godep restore
    - go test -cover -v ./api/... ./gcm/... ./store/... ./model/...

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone

publish:
  gcr:
    when:
      branch: master
    repo: gcr.io/messaging-1174/portal/api
    file: Dockerfile.api
    token: >
      $$GCR_KEY
  gcr:
    when:
      branch: master
    repo: gcr.io/messaging-1174/portal/gcm
    file: Dockerfile.gcm
    token: >
      $$GCR_KEY
