FROM golang:1.5

ENV GOPATH=/

RUN go get github.com/asaskevich/govalidator
RUN go get github.com/google/go-gcm
RUN go get github.com/jinzhu/gorm
RUN go get github.com/lib/pq
RUN go get github.com/mattn/go-sqlite3
RUN go get github.com/satori/go.uuid

RUN mkdir -p /src/portal-server/

COPY gcm/ /src/portal-server/gcm/
COPY model/ /src/portal-server/model/
COPY store/ /src/portal-server/store/

WORKDIR /src/portal-server/

RUN go build -o portalgcm ./gcm

CMD ./portalgcm

